#!/bin/sh

target_workspace=$1
focused_workspace=$(aerospace list-workspaces --focused)

if [ "$focused_workspace" = "$target_workspace" ]; then
    aerospace focus --boundaries workspace --boundaries-action wrap-around-the-workspace dfs-next
else
    aerospace workspace "$target_workspace"
fi
