import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[env]

TERM = "xterm-256color"


[window]

padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1.0
blur = true

option_as_alt = "Both"

[scrolling]

history = 100000

[font]

normal.family = "FiraCode Nerd Font"

size = 19.0

